"""empty message

Revision ID: 216accd1ab9d
Revises: fa0a7ba18f91
Create Date: 2020-10-12 08:13:42.004358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216accd1ab9d'
down_revision = 'fa0a7ba18f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('test', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'test')
    # ### end Alembic commands ###
