"""empty message

Revision ID: 34e9b7d15e05
Revises: 8760c34ade83
Create Date: 2020-10-12 08:39:50.542561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e9b7d15e05'
down_revision = '8760c34ade83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genres')
    op.drop_column('venues', 'genres')
    op.alter_column('venues', 'test', new_column_name='genres')
    op.alter_column('artists', 'test', new_column_name='genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('venues', 'genres', new_column_name='test')
    op.alter_column('artists', 'genres', new_column_name='test')
    # ### end Alembic commands ###
