"""empty message

Revision ID: 5ae9921642c5
Revises: 1a19a39582d3
Create Date: 2020-10-05 10:41:43.389390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae9921642c5'
down_revision = '1a19a39582d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('artists', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    op.drop_column('venues', 'upcoming_shows_count')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'past_shows_count')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'website')
    op.drop_column('artists', 'upcoming_shows_count')
    op.drop_column('artists', 'seeking_venues')
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'past_shows_count')
    # ### end Alembic commands ###
