"""empty message

Revision ID: 692bc9343947
Revises: 25b39982ac31
Create Date: 2020-10-06 12:47:13.976037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692bc9343947'
down_revision = '25b39982ac31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'past_shows_count')
    op.drop_column('artists', 'upcoming_shows_count')
    op.drop_column('venues', 'past_shows_count')
    op.drop_column('venues', 'upcoming_shows_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('upcoming_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('past_shows_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
