"""empty message

Revision ID: 6f0734a979e0
Revises: 9163ba7005e3
Create Date: 2020-10-11 10:05:02.325671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0734a979e0'
down_revision = '9163ba7005e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    op.alter_column('shows', 'test_time', new_column_name='start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('shows', 'start_time', new_column_name='test_time')

    # ### end Alembic commands ###
