"""empty message

Revision ID: e5007837f771
Revises: 57ae73df4eef
Create Date: 2020-10-11 09:55:52.756034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5007837f771'
down_revision = '57ae73df4eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('test_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'test_time')
    # ### end Alembic commands ###
